#config_version=6

show_player:
    mode_attract_started: attract_display_loop
    flipper_cancel:
        attract_display_loop:
            action: advance
images:
    credits:
        load: preload
        file: modes/attract/images/Credits.png

videos:
    mainmenu:
        width: 1920
        height: 1080
        file: modes/attract/videos/MainMenu.mp4
    lastscore:
        width: 1920
        height: 1080
        file: modes/attract/videos/LastScores.mp4
    highscore:
        width: 1920
        height: 1080
        file: modes/attract/videos/HighScores.mp4