#config_version=6

hardware:
    platform: fast

fast:
  net:
    port: /dev/ttyACM0
    controller: neuron
    io_loop:
      3208:
        model: FP-I/O-3208-5
        order: 1
      1616:
        model: FP-I/O-1616
        order: 2

switches:
    s_trough_jam: #used to make sure ball leaves ball trough and enters plunger/launcher lane
        number: 3208-6
        type: 'NC'
    s_trough1: #Opto switch for the first ball in the trough
        number: 3208-7
        type: 'NC'
    s_bonus2:  #Drop target 2 // Upgrade for player ==
        number: 3208-8
    s_bonus1:  #Drop target 1 // Upgrade for player ==
        number: 3208-9
    s_lowerTargets: #Registers as damage to aircraft carrier, all 4 switches as one.
        number: 3208-11
        tags: playfield_active
        debounce: quick
        ignore_window_ms: 1000ms
    s_Lane4: #Right side Entry to top lane on lower playfield
        number: 3208-12
        tags: playfield_active
        debounce: quick
        ignore_window_ms: 1000ms
    s_Lane3: #Right side Entry to bottom lane on lower playfield
        number: 3208-13
        tags: playfield_active
        debounce: quick
        ignore_window_ms: 1000ms
    s_Lane2: #Left side Entry to bottom lane on lower playfield
        number: 3208-14
        tags: playfield_active
        debounce: quick
        ignore_window_ms: 1000ms
    s_Lane1: #Left side entry to top lane on lower playfield
        number: 3208-15
        tags: playfield_active
        debounce: quick
        ignore_window_ms: 1000ms
    s_millPtTarget: #1 million point target
        number: 3208-16
        tags: playfield_active
    s_plunger_lane: # Lets MPF know a ball is readt for launching
        number: 3208-18
    s_bonus3: #Drop Target 3 // Upgrade for player ==
        number: 3208-17
    s_right_flipper_eos: #Triggers when Right Flipper is held up to drop the Power of the coil it hold it up without burnout
        number: 3208-19
    s_left_flipper_eos: #Triggers when Left Flipper is held up to drop the Power of the coil it hold it up without burnout
        number: 23
    s_trough2: #Tracks The Second ball in the trough. Next one to be played
        number: 3208-20
    s_trough3: #Tracks The Third ball in the trough.
        number: 3208-21
    s_trough4: #Tracks The Forth and last ball in the trough. Should be up once first ball in ejected to plunger
        number: 3208-22
    s_launcher_button: #Button used to launch the ball on the cabinet
        number: 3208-24
        debounce: quick
    s_start_button:
        number: 3208-25
        tags: start
    s_right_flipper:
        number: 3208-26
        tags: right_flipper
    s_left_flipper: #internal Name for device (switch in this case)
        number: 3208-27 #hardware pin number for device (switch)
        tags: left_flipper #allows events to play based off cur state


coils:
    c_flipper_left_main:
        number: 0
        default_pulse_ms: 10
        default_hold_power: 0.2
        max_hold_power: 0.5
        allow_enable: true
    c_flipper_right_main:
        number: 3208-5
        default_pulse_ms: 10
        default_hold_power: 0.2
        max_hold_power: 0.5
        allow_enable: true
    c_trough_eject:
        number: 3208-1
        default_pulse_ms: 35
        platform_settings:
            pwm2_ms: 35
    c_autolauncher:
        number: 3208-7
        default_pulse_ms: 20
        platform_settings:
            pwm2_ms: 20
    c_dt_reset:
        number: 1616-13
        default_pulse_ms: 20

drop_targets:
    dt_bonus1_target:
        switch: s_bonus1
    dt_bonus2_target:
        switch: s_bonus2
    dt_bonus3_target:
        switch: s_bonus3

drop_target_banks:
  dt_bonus_bank:
    drop_targets: dt_bonus1_target, dt_bonus2_target, dt_bonus3_target
    reset_coils: c_dt_reset
    reset_on_complete: 1s

#light_stripes:
#    led_uvlightStrip:
#        number_start: 0
#        count: 18
#        number_template: 0-0-{}
#        light_template:
#            type: rgb
#            tags: gi
#    led_playfield_lights:
#        number_start: 19
#        count: 13
#        number_template: 0-0-{}
#        light_template:
#            type: rgb
#            tags: playfieldLEDs

keyboard:
    Q:
        switch: s_left_flipper
    E:
        switch: s_right_flipper
    S:
        switch: s_start_button
    Enter:
        switch: s_launcher_button
    P:
        switch: s_plunger_lane
    U:
        switch: s_trough2
        toggle: true
    I:
        switch: s_trough3
        toggle: true
    O:
        switch: s_trough4
        toggle: true
    M:
        switch: s_lowerTargets
    L:
        switch: s_Lane1
    K:
        switch: s_Lane2
    J:
        switch: s_Lane3
    H:
        switch: s_Lane4

playfields:
    playfield:
        tags: default
        default_source_device: bd_plunger_lane

machine:
    balls_installed: 4

flippers:
    left_flipper:
        main_coil: c_flipper_left_main
        activation_switch: s_left_flipper
        eos_switch: s_left_flipper_eos
        use_eos: true
        repulse_on_eos_open: true
        eos_active_ms_before_repulse: 500
        enable_events: machine_reset_phase_3
        #disable_events: cmd_flipper_disable
        #debug: true
    right_flipper:
        main_coil: c_flipper_right_main
        activation_switch: s_right_flipper
        eos_switch: s_right_flipper_eos
        use_eos: true
        repulse_on_eos_open: true
        eos_active_ms_before_repulse: 500
        enable_events: machine_reset_phase_3
        #disable_events: cmd_flipper_disable
        debug: true

ball_devices:
    bd_trough:
        ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough_jam
        eject_coil: c_trough_eject
        eject_targets: bd_plunger_lane
        mechanical_eject: false
        jam_switch: s_trough_jam
        eject_coil_jam_pulse: 15ms
        tags: trough, home,drain
        eject_timeouts: 3s
        #debug: true
    bd_plunger_lane:
        eject_coil: c_autolauncher
        ball_switches: s_plunger_lane
        mechanical_eject: false
        player_controlled_eject_event: s_launcher_button_active
        eject_targets: playfield
        eject_timeouts: 2s
        #debug: true

displays:
    window:
        width: 800
        height: 600
window:
      title: Victory At Sea
      resizable: true
      fullscreen: false
      borderless: false
      exit_on_escape: true
      source_display: window


slides:
  welcome_slide:
    widgets:
      - type: text
        text: Init DONE!
        font_size: 50
        color: red
      - type: rectangle
        width: 240
        height: 60

slide_player:
  init_done: welcome_slide

sound_system:
    tracks:
        music:
            type: standard
            simultaneous_sounds: 1
            volume: 1
            loop: true

assets:
    sounds:
        default:
            load: on_demand
        music:
            track: music
        main:
            #file: C:/Users/duffb/OneDrive/Documents/Python Envs/PinBallWW2/Machine/modes/attract/sounds/music/main.wav
            file: /home/wicky567/PinballWW2_Master/Machine/modes/attract/sounds/music/main.wav

sound_player:
    mode_attract_started:
        main:
            action: play
    mode_attract_stopped:
        main:
            action: stop

#event_player:
 # mode_attract_started:
  #  - cmd_flipper_disable
  #mode_base_started:
  #  - cmd_flipper_enable

player_vars:
    score:
        initial_value: 0

modes:
    - intro
    - base