#config_version=6

hardware:
    platform: fast

fast:
  net:
    port: /dev/ttyACM0
    controller: neuron
    io_loop:
      3208:
        model: FP-I/O-3208-5
        order: 1
      1616:
        model: FP-I/O-1616
        order: 2

switches:
#3208 switches
    s_trough_jam: #used to make sure ball leaves ball trough and enters plunger/launcher lane
        number: 3208-6
        type: 'NC'
    s_trough1: #Opto switch for the first ball in the trough
        number: 3208-7
        type: 'NC'
    s_bonus2:  #Drop target 2 // Upgrade for player ==
        number: 3208-8
    s_bonus1:  #Drop target 1 // Upgrade for player ==
        number: 3208-9
    s_millPtTarget:  #1 million point target
        number: 3208-10
    s_lowerTargets: #Registers as damage to aircraft carrier, all 4 switches as one.
        number: 3208-11
        tags: playfield_active
    s_Lane4: #Right side Entry to top lane on lower playfield
        number: 3208-12
        tags: playfield_active
    s_Lane3: #Right side Entry to bottom lane on lower playfield
        number: 3208-13
        tags: playfield_active
    s_Lane2: #Left side Entry to bottom lane on lower playfield
        number: 3208-14
        tags: playfield_active
    s_Lane1: #Left side entry to top lane on lower playfield
        number: 3208-15
        tags: playfield_active
    s_right_slingshot: #1 million point target
        number: 3208-17
    s_plunger_lane: # Lets MPF know a ball is readt for launching
        number: 3208-18
    s_right_flipper_eos: #Triggers when Right Flipper is held up to drop the Power of the coil it hold it up without burnout
        number: 3208-19
    s_trough2: #Tracks The Second ball in the trough. Next one to be played
        number: 3208-20
    s_trough3: #Tracks The Third ball in the trough.
        number: 3208-21
    s_trough4: #Tracks The Forth and last ball in the trough. Should be up once first ball in ejected to plunger
        number: 3208-22
    s_launcher_button: #LAUNCH BUTTON
        number: 3208-24
        debounce: quick
    s_start_button: #START BUTTON
        number: 3208-25
        tags: start
    s_right_flipper: # RIGHT FLIPPER SWITCH
        number: 3208-26
        tags: right_flipper
    s_left_flipper: #LEFT FLIPPER SWITCH
        number: 3208-27 
        tags: left_flipper
    s_tilt_bob: #TILT SWITCH
        number: 3208-30
        tags: tilt_warning
#1616 switches
    s_pillbox:
        number: 1616-5
    s_bonus3:  #Drop target 3 // Upgrade for player ==
        number: 1616-6
    s_dive_launch:
        number: 1616-7
    s_dive_hold:
        number: 1616-8
    s_upper_slingshot:
        number: 1616-9
    s_left_upperflipper_eos:
        number: 1616-10
    s_right_diveflipper_eos: #Triggers when Right Flipper is held up to drop the Power of the coil it hold it up without burnout
        number: 1616-11
    s_left_diveflipper_eos: #Triggers when Right Flipper is held up to drop the Power of the coil it hold it up without burnout
        number: 1616-12
    s_popbumper_1:
        number: 1616-13
    s_popbumper_2:
        number: 1616-14
    s_popbumper_3:
        number: 1616-15

coils:
#3208 coils
    c_RtFlipper_upper_main: #RIGHT FLIPPER UPPER
        number: 3208-0
        default_pulse_ms: 20
    c_trough_eject: #TROUGH EJECT
        number: 3208-1
        default_pulse_ms: 35
        platform_settings:
            pwm2_ms: 35
    c_RtFlipper_upper_hold: #RIGHT FLIPPER UPPER
        number: 3208-2
        default_hold_power: .2
        allow_enable: true
    c_autolauncher: #LAUNCHER
        number: 3208-3
        default_pulse_ms: 20
        platform_settings:
            pwm2_ms: 20
    c_right_slingshot: #RIGHT SLING SHOT
        number: 3208-4
        default_pulse_ms: 15
    c_RtFlipper_top_main: #RIGHT FLIPPER TOP
        number: 3208-6
        default_pulse_ms: 20
    c_RtFlipper_top_hold: #RIGHT FLIPPER TOP
        number: 3208-7
        default_hold_power: .2
        allow_enable: true
#1616 coils
    c_dive_launch:
        number: 1616-0
    c_LtDiveFlipper_main:
        number: 1616-1
        default_pulse_ms: 20
    c_Lt_slingshot:
        number: 1616-3
    c_upper_dive_hold:
        number: 1616-4
        default_hold_power: .2
        allow_enable: true
    c_upper_slingshot:
        number: 1616-5
        default_pulse_ms: 15
    c_LtFlipper_upper_hold:
        number: 1616-6
        default_hold_power: .2
    c_LtFlipper_upper_main:
        number: 1616-7
        default_pulse_ms: 20
    c_RtDiveFlipper_hold: #RIGHT DIVE FLIPPER
        number: 1616-8
        default_hold_power: .2
        allow_enable: true
    c_RtDiveFlipper_main: #RIGHT DIVE FLIPPER
        number: 1616-9
        default_pulse_ms: 20
    c_LtDiveFlipper_hold: #LEFT DIVE FLIPPER
        number: 1616-10
        default_hold_power: .2
        allow_enable: true
    c_pillbox:
        number: 1616-11
    c_popbumper_1:
        number: 1616-12
    c_dt_reset: #DROP TARGETS RESET
        number: 1616-13
        default_pulse_ms: 20
    c_popbumper_2:
        number: 1616-14
    c_popbumper_3:
        number: 1616-15

drop_targets:
    dt_bonus1_target:
        switch: s_bonus1
    dt_bonus2_target:
        switch: s_bonus2
    dt_bonus3_target:
        switch: s_bonus3

drop_target_banks:
  dt_bonus_bank:
    drop_targets: dt_bonus1_target, dt_bonus2_target, dt_bonus3_target
    reset_coils: c_dt_reset
    reset_on_complete: 1s

#light_stripes:
#    led_uvlightStrip:
#        number_start: 0
#        count: 18
#        number_template: 0-0-{}
#        light_template:
#            type: rgb
#            tags: gi
#    led_playfield_lights:
#        number_start: 19
#        count: 13
#        number_template: 0-0-{}
#        light_template:
#            type: rgb
#            tags: playfieldLEDs

keyboard:
    Q:
        switch: s_left_flipper
    E:
        switch: s_right_flipper
    S:
        switch: s_start_button
    Enter:
        switch: s_launcher_button
    P:
        switch: s_plunger_lane
    U:
        switch: s_trough2
        toggle: true
    I:
        switch: s_trough3
        toggle: true
    O:
        switch: s_trough4
        toggle: true
    M:
        switch: s_lowerTargets
    L:
        switch: s_bonus1
    K:
        switch: s_bonus2
    J:
        switch: s_bonus3
    H:
        switch: s_millPtTarget
    B:
        switch: s_right_slingshot
    T:
        switch: s_tilt_bob
    Z:
        switch: s_dive_hold
    X:
        switch: s_pillbox

virtual_platform_start_active_switches:
    - s_trough1
    - s_trough2
    - s_trough3
    - s_trough4
    - s_right_flipper_eos

playfields:
    playfield:
        tags: default
        default_source_device: bd_plunger_lane

machine:
    balls_installed: 4

game:
  balls_per_game: 1

flippers:
    left_flipper_upper:
        main_coil: c_LtFlipper_upper_main
        hold_coil: c_LtFlipper_upper_hold
        activation_switch: s_left_flipper
        eos_switch: s_left_upperflipper_eos
        use_eos: true
        repulse_on_eos_open: true
        eos_active_ms_before_repulse: 500
        enable_events: cmd_all_flippers_enable, cmd_upper_flippers_enable
        disable_events: cmd_all_flipper_disable, cmd_upper_flippers_disable
    right_flipper_upper:
        main_coil: c_RtFlipper_upper_main
        hold_coil: c_RtFlipper_upper_hold
        activation_switch: s_right_flipper
        eos_switch: s_right_flipper_eos
        use_eos: true
        repulse_on_eos_open: true
        eos_active_ms_before_repulse: 500
        enable_events: cmd_all_flippers_enable, cmd_upper_flippers_enable
        disable_events: cmd_all_flipper_disable, cmd_upper_flippers_disable
    right_flipper_top:
        main_coil: c_RtFlipper_top_main
        hold_coil: c_RtFlipper_top_hold
        activation_switch: s_right_flipper
        eos_switch: s_right_flipper_eos
        use_eos: true
        repulse_on_eos_open: true
        eos_active_ms_before_repulse: 500
        enable_events: cmd_all_flippers_enable, cmd_upper_flippers_enable
        disable_events: cmd_all_flipper_disable, cmd_upper_flippers_disable
    left_dive_flipper:
        main_coil: c_LtDiveFlipper_main
        hold_coil: c_LtDiveFlipper_hold
        activation_switch: s_left_flipper
        eos_switch: s_left_diveflipper_eos
        use_eos: true
        repulse_on_eos_open: true
        eos_active_ms_before_repulse: 500
        enable_events: cmd_all_flippers_enable, cmd_dive_flippers_enable
        disable_events: cmd_all_flipper_disable, cmd_dive_flippers_disable
    right_dive_flipper:
        main_coil: c_RtDiveFlipper_main
        hold_coil: c_RtDiveFlipper_hold
        activation_switch: s_right_flipper
        eos_switch: s_right_diveflipper_eos
        use_eos: true
        repulse_on_eos_open: true
        eos_active_ms_before_repulse: 500
        enable_events: cmd_all_flippers_enable, cmd_dive_flippers_enable
        disable_events: cmd_all_flipper_disable, cmd_dive_flippers_disable

autofire_coils:
  ac_pillbox:
    coil: c_pillbox
    switch: s_pillbox
  ac_upper_slingshot:
    coil:  c_upper_slingshot
    switch: s_upper_slingshot
  ac_right_slingshot:
    coil: c_right_slingshot
    switch: s_right_slingshot
  ac_popbumper_1:
    coil: c_popbumper_1
    switch: s_popbumper_1
  ac_popbumper_2:
    coil: c_popbumper_2
    switch: s_popbumper_2
  ac_popbumper_3:
    coil: c_popbumper_3
    switch: s_popbumper_3

ball_devices:
    bd_trough:
        ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough_jam
        eject_coil: c_trough_eject
        eject_targets: bd_plunger_lane
        mechanical_eject: false
        jam_switch: s_trough_jam
        eject_coil_jam_pulse: 15ms
        tags: trough, home,drain
        eject_timeouts: 3s
        confirm_eject_type: switch
        confirm_eject_switch: s_plunger_lane
        #debug: true
    bd_plunger_lane:
        eject_coil: c_autolauncher
        ball_switches: s_plunger_lane
        mechanical_eject: false
        player_controlled_eject_event: s_launcher_button_active
        eject_targets: playfield
        eject_timeouts: 500ms
        #debug: true

multiballs:
    mb_MultiBall:
        ball_count: 4
        ball_count_type: add
        shoot_again: 3s
        enable_events: MultiBall_Initiate
        disable_events: Multiball_Disengage
        start_events: MultiBall_Start
        stop_events: MultiBall_Stop

displays:
    window:
        width: 1920
        height: 1080
window:
      title: Victory At Sea
      resizable: true
      fullscreen: false
      borderless: false
      exit_on_escape: true
      source_display: window

widget_styles:
    font_style:
        style: big
        font_name: charlie
        font_size: 60
        color: black
    cur_user:
        color: green
    replaced:
        color: red
    score_size:
        font_size: 45
    name_x:
        x: center - 75
    score_x:
        x: center + 180
    rank_x:
        x: center - 250
    label_y:
        y: center + 53
    score1_y:
        y: center - 28
    score2_y:
        y: center - 115
    score3_y:
        y: center - 202
    score4_y:
        y: center - 289
  
widgets:
    playerscore:
        - type: text
          text: (player_name)
          style: label_y, font_style,name_x
          z: 10
          animations:
            show_slide:
              - property: opacity
                value: 0
                duration: 0.5s
                easing: in_out_quint
              - property: opacity
                value: 1
                duration: 0.5s
                repeat: true
                easing: in_out_quint
        - type: text
          text: (award)
          style: label_y,font_style,rank_x
          z: 10
          animations:
            show_slide:
              - property: opacity
                value: 0
                duration: 0.5s
                easing: in_out_quint
              - property: opacity
                value: 1
                duration: 0.5s
                repeat: true
                easing: in_out_quint
        - type: text
          text: (value)
          style: label_y, font_style,score_x, score_size
          z: 10
          animations:
            show_slide:
              - property: opacity
                value: 0
                duration: 0.5s
                easing: in_out_quint
              - property: opacity
                value: 1
                duration: 0.5s
                repeat: true
                easing: in_out_quint

    highscore1:
        - type: text
          text: (machine|score1_name)
          style: score1_y, font_style,name_x
          z: 10
        - type: text
          text: (machine|score1_label)
          style: score1_y,font_style,rank_x
          z: 10
        - type: text
          text: (machine|score1_value)
          style: score1_y,font_style,score_x, score_size
          z: 10
    highscore2:
        - type: text
          text: (machine|score2_name)
          style: score2_y, font_style,name_x
          z: 10
        - type: text
          text: (machine|score2_label)
          style: score2_y,font_style,rank_x
          z: 10
        - type: text
          text: (machine|score2_value)
          style: score2_y,font_style,score_x, score_size
          z: 10
    highscore3:
        - type: text
          text: (machine|score3_name)
          style: score3_y, font_style,name_x
          z: 10
        - type: text
          text: (machine|score3_label)
          style: score3_y,font_style,rank_x
          z: 10
        - type: text
          text: (machine|score3_value)
          style: score3_y,font_style,score_x, score_size
          z: 10
    highscore4:
        - type: text
          text: (machine|score4_name)
          style: score4_y, font_style,name_x
          z: 10
        - type: text
          text: (machine|score4_label)
          style: score4_y,font_style,rank_x
          z: 10
        - type: text
          text: (machine|score4_value)
          style: score4_y,font_style,score_x, score_size
          z: 10


slides:
  welcome_slide:
    widgets:
      - type: text
        text: Init DONE!
        font_size: 50
        color: red
      - type: rectangle
        width: 240
        height: 60

slide_player:
  init_done: welcome_slide

sound_system:
    tracks:
        music:
            type: standard
            simultaneous_sounds: 1
            volume: 1
            loop: true

sound_player:
    mode_attract_started:
        main:
            action: play
    mode_attract_stopped:
        main:
            action: stop

images:
    highscore_initials:
        load: preload
        file: /home/wicky567/PinballWW2_Master/Machine/modes/high_score/images/Highscore_initials.png
        #file: C:/Users/duffb/Documents/Python Envs/PinBallWW2/Machine/modes/high_score/images/Highscore_initials.png

event_player:
   mode_attract_started:
        - cmd_all_flippers_disable
   ball_will_start:
        - cmd_upper_flippers_enable
   mode_base_started:
        - cmd_upper_flippers_enable
        - cmd_dive_flippers_disable
   mode_dive_started:
        - cmd_dive_flippers_enable
        - cmd_upper_flippers_disable
   dive_detection_done:
        - cmd_eject_dive_ball
   torpedos_Complete:
        - cmd_dive_flippers_disable
   mode_dive_ended:
        - cmd_upper_flippers_enable
        - cmd_release_upper_ball
   tilt:
        - cmd_all_flippers_disable
   game_ended:
        - cmd_all_flippers_disable
   timer_dive_detect_complete:
        - dive_detection_done

coil_player:
    cmd_eject_dive_ball:
        c_dive_launch: pulse
    s_dive_hold_active:
        c_upper_dive_hold:
            action: enable
            hold_power: .2
    mode_dive_stopped:
        c_upper_dive_hold:
            action: disable
player_vars:
    score:
        value_type: int
        initial_value: 0
    level:
        value_type: int
        initial_value: 0
    multiplier:
        value_type: int
        initial_value: 1
    rank:
        value_type: str
        initial_value: BOOTCAMP
    mb_time:
        value_type: int
        initial_value: 99
    mb_curTime:
        value_type: int
        initial_value: 0
    dive_lvl:
        value_type: int
        initial_value: 0
    torpedos_goal:
        value_type: int
        initial_value: 0
    torpedo_hits:
        value_type: int
        initial_value: 0
    cur_drinks:
        value_type: int
        initial_value: 0

modes:
    - tilt
    - base
    - dive
    - restrelax
    - level1
    - level2
    - level3
    - high_score
    - multiball