#config_version=6

mode:
    start_events: ball_started
    stop_events: Intro_end
    priority: 200  #(100 - 1,000,000)

show_player:
    mode_intro_started: 
        intro_display_loop:
            loops: 0
            events_when_completed: Intro_end
    mode_intro_started.1: intro_show

