#config_version=6

mode:
    start_events: mode_intro_stopped
    priority: 100  #(100 - 1,000,000)
  
slide_player:
    mode_base_started:
        widgets:
          - type: text
            text: (score)
            number_grouping: true
            min_digits: 2
            font_size: 100
          - type: text
            text: PLAYER (ball)
            y: 10
            x: 10
            font_size: 50
            anchor_x: left
            anchor_y: bottom
          - type: text
            text: BALL (number)
            y: 10
            x: right-10
            anchor_x: right
            anchor_y: bottom
            font_size: 50

variable_player:
    s_Target1_active:
        score: 250
    s_Target2_active:
        score: 500
    s_Target3_active:
        score: 1000
    s_Target4_active:
        score: 1500