#config_version=6

mode:
    start_events: ball_started
    priority: 100  #(100 - 1,000,000)

variable_player:
    s_lowerTargets_active:
        score: 1250
    s_right_slingshot_active:
        score: 1500
    s_popbumper_1_active:
        score: 10000
    s_popbumper_2_active:
        score: 10000
    s_popbumper_3_active:
        score: 10000