#config_version=6

mode:
    start_events: ball_started
    priority: 100  #(100 - 1,000,000)

variable_player:
    s_lowerTargets_active:
        score: 1250 * current_player.multiplier
    s_right_slingshot_active:
        score: 1500 * current_player.multiplier
    s_popbumper_1_active:
        score: 10000 * current_player.multiplier
    s_popbumper_2_active:
        score: 10000 * current_player.multiplier
    s_popbumper_3_active:
        score: 10000 * current_player.multiplier
    s_bonus1_active:
        score: 10000
        multiplier:
            int: 2
            action: set
    s_bonus2_active:
        score: 10000
        multiplier:
            int: 3
            action: set
    s_bonus3_active:
        score: 10000
        multiplier: 
            int: 4
            action: set
    s_millPtTarget_active:
        score: 1000000